version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 2
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
      minor-patch-deps:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      major-deps:
        patterns:
          - "*"
        update-types:
          - "major"
